### ISSUE TITLE
Ten Crop

### ISSUE THREAD

**Issue by haohang96** [neuroailab/LocalAggregation-Pytorch#3]
Is tencrop is applied in report results of the paper? I find that tf-implementation set ten-crop as True, however torch-implementation set ten-crop as False.

**Comment by chengxuz** [comment]
The paper reports both ten crop results and single-crop results (see ICCV version, ten crop is reported in the main text and single crop is reported in the appendix). You can change the setting according to your interest.

**Comment by haohang96** [comment]
I can not find the version that single crop is reported, can you provide a link?

**Comment by haohang96** [comment]
OK, I find it. http://openaccess.thecvf.com/content_ICCV_2019/supplemental/Zhuang_Local_Aggregation_for_ICCV_2019_supplemental.pdf
Thanks !
